"""ヘッダのボタン文言とキーボード選択幅の共通定数。"""

CAPTURE_IDLE_TEXT = "キー入力で取得"
CAPTURE_ACTIVE_TEXT = "取得中…（Escで停止）"
CAPTURE_TEXTS = (CAPTURE_IDLE_TEXT, CAPTURE_ACTIVE_TEXT)

HOOK_START_TEXT = "開始（フックON）"
HOOK_STOP_TEXT = "停止（フックOFF）"
HOOK_TOGGLE_TEXTS = (HOOK_START_TEXT, HOOK_STOP_TEXT)

TRIGGER_DISABLE_TEXT = "通常トリガー無効化"
TRIGGER_ENABLE_TEXT = "通常トリガー有効化"
TRIGGER_TOGGLE_TEXTS = (TRIGGER_DISABLE_TEXT, TRIGGER_ENABLE_TEXT)

KEYBOARD_LAYOUT_COMBO_WIDTH = 12
